services:
  webtop-550e8400:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop_guillaume_dev
    environment:
      - PGID=1000
      - PUID=1000
      - TITLE=Guillaume-Webtop
      - TZ=America/Toronto
    volumes:
      - /home/guillaume/webtop/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: 1gb
    restart: unless-stopped