services:
  webtop-0365babf:
    image: webtop
    container_name: lscr.io/linuxserver/webtop:latest
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
    volumes:
      - custom/path:/
    ports:
      - 3000:3000
      - 3001:3001
      - 800:0
    shm_size: 1gb
    restart: on-failure